export const GET_SUGGESTION = "GET_SUGGESTION";
export const GET_SUGGESTIONS = "GET_SUGGESTIONS";
export const ADD_SUGGESTION = "ADD_SUGGESTION";
export const UPDATE_SUGGESTION = "UPDATE_SUGGESTION";
