# Generated by Django 4.1.2 on 2022-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description placeholder', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default='ingredients placeholder', max_length=255),
        ),
    ]
