# Generated by Django 4.1.2 on 2022-10-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0002_product_description_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='date',
            field=models.CharField(default='date placeholder', max_length=255),
        ),
        migrations.AddField(
            model_name='opinion',
            name='description',
            field=models.CharField(default='description placeholder', max_length=255),
        ),
    ]
