# Generated by Django 4.1.2 on 2022-10-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0003_opinion_date_opinion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
    ]
