# Generated by Django 4.1.2 on 2022-12-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0005_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
