# Generated by Django 4.1.2 on 2022-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0005_user_date_joined_user_password_hash_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='---', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Miscellaneous', max_length=100),
        ),
    ]
