# Generated by Django 4.1.2 on 2022-12-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0009_historicalproduct_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='opcol.category'),
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('product', 'created_by')},
        ),
    ]
