# Generated by Django 4.1.2 on 2022-12-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0010_alter_category_parent_alter_opinion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='is_considered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_positive', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcol.category')),
            ],
        ),
        migrations.AddField(
            model_name='opinion',
            name='negative_features',
            field=models.ManyToManyField(related_name='negative_features', to='opcol.feature'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='positive_features',
            field=models.ManyToManyField(related_name='positive_features', to='opcol.feature'),
        ),
    ]
