# Generated by Django 4.1.2 on 2022-12-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0011_suggestion_is_considered_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='negative_features',
            field=models.ManyToManyField(blank=True, related_name='negative_features', to='opcol.feature'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='positive_features',
            field=models.ManyToManyField(blank=True, related_name='positive_features', to='opcol.feature'),
        ),
    ]
