# Generated by Django 4.1.2 on 2022-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0012_alter_opinion_negative_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='description',
            field=models.CharField(blank=True, default='This description is empty.', max_length=255),
        ),
    ]
