# Generated by Django 4.1.2 on 2022-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcol', '0013_alter_opinion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
